name: "Cupypi Publish Python Package"
description: "Publish your python project to pypi quickly. (using token)"
author: "GitLabBR"



runs:
  using: node16
  main: dist/index.js
branding:
  icon: shield
  color: red
