name: Cupypi Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Start up python
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install build
        python -m pip install twine
    - name: Build Pypi Project
      run: |
        python -m build
    - name: Publish Package
      run: |
        twine upload dist/*
    - name: Finish
      run: echo "Project was been published! ${{ github.action }}"

