name: "Check dir/file"
on: 
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout plugin
      uses: actions/checkout@v4
    - name: Check dirs and files
      uses: ./
      with:
        password: ${{ secrets.CPYPI_API_TOKEN }}