name: "Check dir/file"
on: 
  release:
    types: [published]
    
  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Dirs and files
      uses: actions/checkout@v4.2.2
    - name: Logs
      run: echo "Checkout done."
    - name: Go to base dir
      run: |
        cd "/home/runner/work/${{ github.event.repository.name }}"
        echo "Current dir: $(pwd)"
        echo "Delete any duplicate repo dirs like: (owner/example) duplicate: (example/example)"
    - name: Setup python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'
    - name: Setup pip
      run: python -m pip install --upgrade pip
    - name: Install twine & Upgrade (Package)
      run: |
        python -m pip install twine
        python -m pip install --upgrade twine
    - name: Publish Project
      run: python -m twine upload dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.password }}
        TWINE_USERNAME: ${{ secrets.username }}
    - name: Finish
      run: echo "Finished with success."
