name: "Get file"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout plugin
      uses: actions/checkout@v4
    - name: Check dirs and files
      uses: ./
    - name: Go to the test folder
      run: cd test
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Configure pip 
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
       python -m pip install build
    - name: Build package 
      run: python -m build 
    - name: Upload package 
      uses: pypa/gh-action-pypi-publish@release/v1 
      with:
        password: ${{ secrets.CPYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
      
      
