name: "Check dir/file"
on: 
  release:
    types: [published]
    
  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Dirs and files
      uses: actions/checkout@v4
    - name: Logs
      run: echo "Checkout done."
    - name: Go to base dir
      run: |
        cd "/home/runner/work/${{ github.event.repository.name }}"
        echo "Current dir: $(pwd)"
        echo "Delete any duplicate repo dirs like: (owner/example) duplicate: (example/example)"
    - name: Finish
      run: echo "Finished with success."
