name: "Check dir/file"
on: 
  workflow_dispatch:
    inputs:
      password:
        description: "Your pypi token"
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout plugin
      uses: actions/checkout@v4
    - name: Echo
      run: echo "Checkout Loaded."
    - name: Check dirs and files
      uses: ./
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
