name: "Check dir/file"
on: 
  release:
    types: [published]
    
  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Dirs and files
      uses: actions/checkout@v4
    - name: Logs
      run: echo "Checkout done."
    
